version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Release
- Debug

cache:
- build/lib -> appveyor.yml

before_build:
- cmd: >-
    git submodule update --init --recursive
    
    cmake -G "Visual Studio 15 2017 Win64"
    
build:
  project: build/Games_Engineering.sln
  parallel: true
  verbosity: minimal